#服务注册中心实例的主机名
spring:
  application:
    name: service-eureka
  profiles: peer1
server:
  port: 4001
eureka:
  instance:
    hostname: peer1
  client:
    #是否向服务注册中心注册自己
    registerWithEureka: true
    #是否检索服务
    fetchRegistry: true
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://peer2:4002/eureka/,http://peer3:4003/eureka/
---

spring: 
  application:
    name: service-eureka
  profiles: peer2
server:
  port: 4002
eureka:
  instance:
    hostname: peer2
  client:
    #是否向服务注册中心注册自己
    registerWithEureka: true
    #是否检索服务
    fetchRegistry: true
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://peer1:4001/eureka/,http://peer3:4003/eureka/
---

spring: 
  application:
    name: service-eureka
  profiles: peer3
server:
  port: 4003
eureka:
  instance:
    hostname: peer3
  client:
    #是否向服务注册中心注册自己
    registerWithEureka: true
    #是否检索服务
    fetchRegistry: true
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://peer1:4001/eureka/,http://peer2:4002/eureka/