#服务注册中心端口号
server:
  port: 3000

#服务注册中心实例的主机名
eureka:
  instance:
    hostname: localhost
  client:
    #是否向服务注册中心注册自己
    registerWithEureka: false
    #是否检索服务
    fetchRegistry: false
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/